#!/bin/bash
# 脚本公用的functions
game_status(){
    ps fax |grep $1|grep -v grep|wc -l
}
gamePort_status(){
    netstat -tpln|grep $1|wc -l
}
tick_status(){
    ps fax |grep nnSer|grep -v grep|wc -l
}
color(){
    echo -e "\033[3$1m $2\033[0m"
}

detect(){
    if [ $1 -eq $2 ];then
	color 4 "$3 正常"
    else
	color 1 "$3 异常"
    fi
}

