1%game-center-react%react.sh%react.sh%apia apix%/data/Rollback%/data/fe/game-center-react/
2%pkgame-libs%jslib.sh%jslib.sh%xkdev%/data/Rollback%/data/fe/jssdk/0.0.1/pkgame-libs/
3%upload%upload.sh%upload.sh%apia apix%/data/Rollback%/data/www/upload/
4%admin%admin.sh%admin.sh%apia apix%/data/Rollback%/data/www/game/admin/
5%game_manager%game_manager.sh%game_manager.sh%apia apix%/data/Rollback%/data/www/game/game_manager/
6%api%api.sh%api.sh%apia apix%/data/Rollback%/data/www/game/api/
7%php-framework%phpframework.sh%phpframework.sh%apia apix servicea%/data/Rollback%/data/www/game/php-framework/
8%service%service.sh%service.sh%servicea%/data/Rollback%/data/www/game/service/
