1%game-center-react%apia%apia apix www%/data/fe/bak%game
2%pkgame-libs%xkdev%xkdev%/data/fe/jssdk/0.0.1/pkgame-libs/bak%root
3%upload%apia%apia apix%/data/www/game/bak%game
4%admin%apia%apia apix%/data/www/game/bak%game
5%game_manager%apia%apia apix%/data/www/game/bak%game
6%api%apia%apia apix www%/data/www/game/bak%game
7%php-framework%apia%apia apix www servicea%/data/www/game/bak%game
8%service%servicea%servicea%/data/www/game/bak%game
9%test1%xkdev%xkdev%/tmp/bak%root
