1%game-center-react%apia%apia apix www%/data/fe/bak
2%pkgame-libs%xkdev%xkdev%/data/fe/jssdk/0.0.1/pkgame-libs/bak
3%upload%apia%apia apix%/data/www/game/bak
4%admin%apia%apia apix%/data/www/game/bak
5%game_manager%apia%apia apix%/data/www/game/bak
6%api%apia%apia apix www%/data/www/game/bak
7%php-framework%apia%apia apix www servicea%/data/www/game/bak
8%service%servicea%servicea%/data/www/game/bak